export {default as logo2} from "./vera_films.png"
export {default as logo} from "./logo.png"
export {default as video} from "./play.svg"
export {default as star} from "./star.svg"
export {default as starDark} from "./star_dark.svg"