

export const filmConstants = {
    FETCH_PAGINATED_FILMS : 'FETCH_PAGINATED_FILMS',
    FETCHING_PAGINATED_FILMS : 'FETCHING_PAGINATED_FILM',
    ALL_FILM_PAGINATION: 'ALL_FILM_PAGINATION',


    CREATE_NEW_FILM : 'CREATE_NEW_FILM',
    CREATING_NEW_FILM: 'CREATING_NEW_FILM',


    FETCH_FILM_BY_ID: 'FETCH_FILM_BY_ID',
    FETCHING_FILM_BY_ID: 'FETCHING_FILM_BY_ID',

    UPDATE_FILM_BY_ID: 'UPDATE_FILM_BY_ID',
    UPDATING_FILM_BY_ID: 'UPDATING_FILM_BY_ID',

    SET_SEARCH: 'SET_SEARCH',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_NAV : 'SET_NAV',
    SET_CONTENT_TYPE: 'SET_CONTENT_TYPE'
}
export default filmConstants