

export const filmConstants = {
    FETCH_PAGINATED_FILMS : 'FETCH_PAGINATED_FILMS',
    FETCHING_PAGINATED_FILMS : 'FETCHING_PAGINATED_FILM',

    FETCH_FILM_BY_ID: 'FETCH_FILM_BY_ID',
    FETCHING_FILM_BY_ID: 'FETCHING_FILM_BY_ID',

    UPDATE_FILM_BY_ID: 'UPDATE_FILM_BY_ID',
    UPDATING_FILM_BY_ID: 'UPDATING_FILM_BY_ID',


    SET_NAV : 'SET_NAV',
    SET_CONTENT_TYPE: 'SET_CONTENT_TYPE'
}
export default filmConstants